insert into programFinance (program_programId, payPerDay, typeOfWork) values (2, 20, 'Etiam vel augue.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (3, 25, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (4, 15, 'Morbi quis tortor id nulla ultrices aliquet.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (7, 20, 'Morbi porttitor lorem id ligula.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (9, 15, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (10, 15, 'Donec posuere metus vitae ipsum.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (11, 20, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (12, 15, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (13, 10, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (15, 20, 'Donec ut mauris eget massa tempor convallis.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (16, 20, 'Etiam faucibus cursus urna.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (17, 15, 'Etiam pretium iaculis justo.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (19, 10, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (22, 25, 'Vestibulum sed magna at nunc commodo placerat.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (25, 25, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (28, 25, 'Quisque porta volutpat erat.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (30, 25, 'Curabitur in libero ut massa volutpat convallis.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (32, 20, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (33, 30, 'Suspendisse ornare consequat lectus.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (35, 15, 'Suspendisse potenti.');
insert into programFinance (program_programId, payPerDay, typeOfWork) values (36, 10, 'Pellentesque ultrices mattis odio.');
